const app=document.querySelector('#app');let state={me:null,view:'overview'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch('./api'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
async function bootstrap(){const token=new URLSearchParams(location.search).get('token');if(token){try{await api('/session',{method:'POST',body:JSON.stringify({token})});history.replaceState({},'',location.pathname)}catch(e){return login('The administration handoff is invalid or expired.')}}try{state.me=await api('/me');render();loadView()}catch(e){login('Open Administration from the Nord Forge Platform Owner button.')}} 
function login(msg){app.innerHTML=`<div class="login"><div class="login-card"><div class="mark">N</div><h1>Forge Administration</h1><p>${esc(msg)}</p></div></div>`}
function render(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="mark">N</div><div>Nord Forge<small>Administration</small></div></div><div class="nav">
<button data-v="overview" class="active"><i class="fa-solid fa-chart-line"></i><span>Overview</span></button>
<button data-v="users"><i class="fa-solid fa-users"></i><span>Users</span></button>
<button data-v="workspaces"><i class="fa-solid fa-layer-group"></i><span>Workspaces</span></button>
<button data-v="runtime"><i class="fa-solid fa-microchip"></i><span>Runtime</span></button>
<button data-v="updates"><i class="fa-solid fa-cloud-arrow-down"></i><span>Updates</span></button>
<button data-v="audit"><i class="fa-solid fa-clock-rotate-left"></i><span>Audit</span></button>
<button data-v="maintenance"><i class="fa-solid fa-shield-halved"></i><span>Maintenance</span></button></div><div class="spacer"></div>
<div class="operator"><b>${esc(state.me.email)}</b><br>Platform Owner session</div></aside><main><div class="top"><div><div class="eyebrow">Nord System</div><h1 id="title">Administration</h1></div><button class="btn" id="logout"><i class="fa-solid fa-arrow-right-from-bracket"></i> Sign out</button></div><div id="content"></div></main></div>`;
document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x===b));loadView()});document.querySelector('#logout').onclick=async()=>{await api('/session',{method:'DELETE'});login('Administration session closed.')}}
async function loadView(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Loading…</div>';try{if(state.view==='overview')return overview(await api('/summary'));if(state.view==='users')return users(await api('/users'));if(state.view==='workspaces')return workspaces(await api('/workspaces'));if(state.view==='runtime')return runtime(await api('/runtime'));if(state.view==='updates')return updates(await api('/system/update'));if(state.view==='audit')return audit(await api('/audit'));if(state.view==='maintenance')return maintenance(await api('/summary'))}catch(e){c.innerHTML='<div class="notice">Core service unavailable or the session expired.</div>'}}
function overview(d){document.querySelector('#title').textContent='Platform overview';document.querySelector('#content').innerHTML=`<div class="grid">${[['Users',d.users],['Workspaces',d.workspaces],['Products',d.products],['Active licenses',d.active_licenses],['Published',d.published_products],['Open support',d.open_support],['Open purchases',d.open_purchases]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="section"><div class="section-head"><h2>Recent workspaces</h2></div>${table(d.workspaces_recent,['name','owner_email','status','created_at'])}</div>`}
function users(rows){document.querySelector('#title').textContent='Users';document.querySelector('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Platform accounts</h2><span class="pill">${rows.length} users</span></div><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Forge Key</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.display_name)}</td><td>${esc(r.email)}</td><td>${esc(r.forge_key)}</td><td><span class="pill ${r.status==='active'?'good':''}">${esc(r.status)}</span></td><td>${esc(r.created_at)}</td><td>${r.platform_owner?'<span class="pill">Owner</span>':'<button class="btn" data-user-status="'+r.id+'" data-next="'+(r.status==='active'?'suspended':'active')+'">'+(r.status==='active'?'Suspend':'Activate')+'</button>'}</td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-user-status]').forEach(b=>b.onclick=async()=>{await api('/users/'+b.dataset.userStatus+'/status',{method:'PUT',body:JSON.stringify({status:b.dataset.next})});users(await api('/users'))})}
function workspaces(rows){document.querySelector('#title').textContent='Workspaces';document.querySelector('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Developer workspaces</h2><span class="pill">${rows.length} workspaces</span></div><table class="table"><thead><tr><th>Name</th><th>Slug</th><th>Owner</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.slug)}</td><td>${esc(r.owner_email)}</td><td><span class="pill ${r.status==='active'?'good':''}">${esc(r.status)}</span></td><td>${esc(r.created_at)}</td><td><button class="btn" data-workspace-status="${r.id}" data-next="${r.status==='active'?'suspended':'active'}">${r.status==='active'?'Suspend':'Activate'}</button></td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-workspace-status]').forEach(b=>b.onclick=async()=>{await api('/workspaces/'+b.dataset.workspaceStatus+'/status',{method:'PUT',body:JSON.stringify({status:b.dataset.next})});workspaces(await api('/workspaces'))})}
function runtime(d){document.querySelector('#title').textContent='Runtime';const used=Math.max(0,Number(d.memory_total||0)-Number(d.memory_free||0));document.querySelector('#content').innerHTML=`<div class="grid"><div class="metric"><span>Forge version</span><strong>${esc(d.version)}</strong></div><div class="metric"><span>Java</span><strong style="font-size:18px">${esc(d.java)}</strong></div><div class="metric"><span>Processors</span><strong>${esc(d.processors)}</strong></div><div class="metric"><span>Heap in use</span><strong style="font-size:18px">${(used/1024/1024).toFixed(0)} MB</strong></div></div><div class="section"><div class="section-head"><h2>Runtime state</h2></div><div style="padding:18px"><span class="pill ${d.maintenance?'':'good'}">${d.maintenance?'MAINTENANCE':'HEALTHY'}</span><p style="color:var(--muted)">Administration runs as a separate service and communicates with Core through the internal service secret.</p></div></div>`}
function updates(d){document.querySelector('#title').textContent='Updates';const s=d.status||{};const stateText=d.queued?'queued':(s.state||'idle');document.querySelector('#content').innerHTML=`<div class="notice">Updates are executed by a separate root systemd worker. The Administration Java service never receives sudo or direct root privileges.</div><div class="grid"><div class="metric"><span>Installed version</span><strong>${esc(d.version)}</strong></div><div class="metric"><span>Update state</span><strong style="font-size:18px">${esc(stateText)}</strong></div><div class="metric"><span>Backups</span><strong>${(d.backups||[]).length}</strong></div></div><div class="section"><div class="section-head"><div><h2>Trusted update transaction</h2><p>Resolve pinned GitHub commit → build → snapshot → deploy → health-check → automatic rollback.</p></div><button class="btn primary" id="run-update" ${stateText==='running'||stateText==='queued'?'disabled':''}>Run update</button></div><div style="padding:18px"><p style="color:var(--muted)">${esc(s.message||'No update has been executed from this Administration installation yet.')}</p><small style="color:var(--muted)">${esc(s.updated_at||'')}</small></div></div><div class="section"><div class="section-head"><h2>Recent snapshots</h2></div>${table(d.backups||[],['name','size','modified_at'])}</div><div class="section"><div class="section-head"><h2>Update log</h2><button class="btn" id="load-update-log">Load log</button></div><pre id="update-log" style="margin:0;padding:18px;white-space:pre-wrap;color:var(--muted);font-size:11px;max-height:360px;overflow:auto">Log is loaded on demand.</pre></div>`;const run=document.querySelector('#run-update');if(run)run.onclick=async()=>{run.disabled=true;run.textContent='Queued';try{await api('/system/update',{method:'POST',body:'{}'});setTimeout(()=>loadView(),1200)}catch(e){run.disabled=false;run.textContent='Run update'}};document.querySelector('#load-update-log').onclick=async()=>{try{const x=await api('/system/update/log');document.querySelector('#update-log').textContent=x.log||'No log yet.'}catch(e){document.querySelector('#update-log').textContent='Update log unavailable.'}}}
function audit(rows){document.querySelector('#title').textContent='Audit';document.querySelector('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Platform audit</h2><span class="pill">${rows.length} events</span></div>${table(rows,['action','workspace_name','email','target','details','created_at'])}</div>`}
function maintenance(d){document.querySelector('#title').textContent='Maintenance';const on=String(d.maintenance)==='true';document.querySelector('#content').innerHTML=`<div class="notice">Maintenance state is controlled centrally and applies to platform operations. Use this deliberately.</div><div class="section"><div class="section-head"><h2>Platform maintenance</h2><span class="pill ${on?'':'good'}">${on?'ENABLED':'ONLINE'}</span></div><div style="padding:18px"><p style="color:var(--muted)">Current state: <b>${on?'maintenance':'normal operation'}</b></p><button class="btn ${on?'':'primary'}" id="toggle-maint">${on?'Disable maintenance':'Enable maintenance'}</button></div></div>`;document.querySelector('#toggle-maint').onclick=async()=>{await api('/maintenance',{method:'PUT',body:JSON.stringify({enabled:!on})});loadView()}}
function table(rows,cols){if(!rows?.length)return '<div class="empty">No data yet.</div>';return `<table class="table"><thead><tr>${cols.map(c=>`<th>${c.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='status'?'<span class="pill">'+esc(r[c])+'</span>':esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
bootstrap();
