const app=document.querySelector('#app');let state={me:null,view:'overview'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch('/api'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
async function bootstrap(){const token=new URLSearchParams(location.search).get('token');if(token){try{await api('/session',{method:'POST',body:JSON.stringify({token})});history.replaceState({},'',location.pathname)}catch(e){return login('The administration handoff is invalid or expired.')}}try{state.me=await api('/me');render();loadView()}catch(e){login('Open Administration from the Nord Forge Platform Owner button.')}} 
function login(msg){app.innerHTML=`<div class="login"><div class="login-card"><div class="mark">N</div><h1>Forge Administration</h1><p>${esc(msg)}</p></div></div>`}
function render(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="mark">N</div><div>Nord Forge<small>Administration</small></div></div><div class="nav">
<button data-v="overview" class="active"><i class="fa-solid fa-chart-line"></i><span>Overview</span></button>
<button data-v="users"><i class="fa-solid fa-users"></i><span>Users</span></button>
<button data-v="workspaces"><i class="fa-solid fa-layer-group"></i><span>Workspaces</span></button>
<button data-v="maintenance"><i class="fa-solid fa-shield-halved"></i><span>Maintenance</span></button></div><div class="spacer"></div>
<div class="operator"><b>${esc(state.me.email)}</b><br>Platform Owner session</div></aside><main><div class="top"><div><div class="eyebrow">Nord System</div><h1 id="title">Administration</h1></div><button class="btn" id="logout"><i class="fa-solid fa-arrow-right-from-bracket"></i> Sign out</button></div><div id="content"></div></main></div>`;
document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x===b));loadView()});document.querySelector('#logout').onclick=async()=>{await api('/session',{method:'DELETE'});login('Administration session closed.')}}
async function loadView(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Loading…</div>';try{if(state.view==='overview')return overview(await api('/summary'));if(state.view==='users')return users(await api('/users'));if(state.view==='workspaces')return workspaces(await api('/workspaces'));if(state.view==='maintenance')return maintenance(await api('/summary'))}catch(e){c.innerHTML='<div class="notice">Core service unavailable or the session expired.</div>'}}
function overview(d){document.querySelector('#title').textContent='Platform overview';document.querySelector('#content').innerHTML=`<div class="grid">${[['Users',d.users],['Workspaces',d.workspaces],['Products',d.products],['Active licenses',d.active_licenses],['Published',d.published_products],['Open support',d.open_support],['Open purchases',d.open_purchases]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="section"><div class="section-head"><h2>Recent workspaces</h2></div>${table(d.workspaces_recent,['name','owner_email','status','created_at'])}</div>`}
function users(rows){document.querySelector('#title').textContent='Users';document.querySelector('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Platform accounts</h2><span class="pill">${rows.length} users</span></div>${table(rows,['display_name','email','forge_key','status','created_at'])}</div>`}
function workspaces(rows){document.querySelector('#title').textContent='Workspaces';document.querySelector('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Developer workspaces</h2><span class="pill">${rows.length} workspaces</span></div>${table(rows,['name','slug','owner_email','status','created_at'])}</div>`}
function maintenance(d){document.querySelector('#title').textContent='Maintenance';const on=String(d.maintenance)==='true';document.querySelector('#content').innerHTML=`<div class="notice">Maintenance state is controlled centrally and applies to platform operations. Use this deliberately.</div><div class="section"><div class="section-head"><h2>Platform maintenance</h2><span class="pill ${on?'':'good'}">${on?'ENABLED':'ONLINE'}</span></div><div style="padding:18px"><p style="color:var(--muted)">Current state: <b>${on?'maintenance':'normal operation'}</b></p><button class="btn ${on?'':'primary'}" id="toggle-maint">${on?'Disable maintenance':'Enable maintenance'}</button></div></div>`;document.querySelector('#toggle-maint').onclick=async()=>{await api('/maintenance',{method:'PUT',body:JSON.stringify({enabled:!on})});loadView()}}
function table(rows,cols){if(!rows?.length)return '<div class="empty">No data yet.</div>';return `<table class="table"><thead><tr>${cols.map(c=>`<th>${c.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='status'?'<span class="pill">'+esc(r[c])+'</span>':esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
bootstrap();
