package com.nordlab.forge;

import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

@ApplicationScoped
public class Database {
    @Inject DataSource dataSource;

    void onStart(@Observes StartupEvent ignored) {
        List<String> ddl = List.of(
            "CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,email VARCHAR(320) NOT NULL UNIQUE,display_name VARCHAR(120) NOT NULL,password_hash VARCHAR(500) NOT NULL,forge_key VARCHAR(80) NOT NULL UNIQUE,platform_owner BOOLEAN NOT NULL DEFAULT FALSE,status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS sessions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,token_hash VARCHAR(128) NOT NULL UNIQUE,csrf_token VARCHAR(128) NOT NULL,expires_at TIMESTAMP WITH TIME ZONE NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS workspaces (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id BIGINT NOT NULL,name VARCHAR(120) NOT NULL,slug VARCHAR(120) NOT NULL UNIQUE,status VARCHAR(24) NOT NULL DEFAULT 'active',store_name VARCHAR(160),store_description CLOB,store_currency VARCHAR(8) NOT NULL DEFAULT 'EUR',store_theme VARCHAR(16) NOT NULL DEFAULT 'dark',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS workspace_members (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,user_id BIGINT NOT NULL,role VARCHAR(32) NOT NULL DEFAULT 'viewer',permissions CLOB,status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,user_id))",
            "CREATE TABLE IF NOT EXISTS products (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,name VARCHAR(160) NOT NULL,slug VARCHAR(160) NOT NULL,description CLOB,category VARCHAR(80),price_cents BIGINT NOT NULL DEFAULT 0,currency VARCHAR(8) NOT NULL DEFAULT 'EUR',license_required BOOLEAN NOT NULL DEFAULT TRUE,protection_mode VARCHAR(32) NOT NULL DEFAULT 'LICENSE_ONLY',status VARCHAR(24) NOT NULL DEFAULT 'draft',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,slug))",
            "CREATE TABLE IF NOT EXISTS releases (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_id BIGINT NOT NULL,version VARCHAR(64) NOT NULL,changelog CLOB,file_name VARCHAR(255) NOT NULL,storage_path VARCHAR(1000) NOT NULL,published BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(product_id,version))",
            "CREATE TABLE IF NOT EXISTS entitlements (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,source VARCHAR(32) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,product_id))",
            "CREATE TABLE IF NOT EXISTS licenses (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,license_key VARCHAR(100) NOT NULL UNIQUE,status VARCHAR(24) NOT NULL DEFAULT 'active',server_limit INT NOT NULL DEFAULT 1,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,product_id))",
            "CREATE TABLE IF NOT EXISTS license_activations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,license_id BIGINT NOT NULL,server_id VARCHAR(180) NOT NULL,keymaster VARCHAR(220),last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,revoked BOOLEAN NOT NULL DEFAULT FALSE,UNIQUE(license_id,server_id))",
            "CREATE TABLE IF NOT EXISTS download_tokens (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,release_id BIGINT NOT NULL,token_hash VARCHAR(128) NOT NULL UNIQUE,expires_at TIMESTAMP WITH TIME ZONE NOT NULL,used_at TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE IF NOT EXISTS docs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,title VARCHAR(180) NOT NULL,slug VARCHAR(180) NOT NULL,body CLOB,published BOOLEAN NOT NULL DEFAULT FALSE,updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,slug))",
            "CREATE TABLE IF NOT EXISTS site_pages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,title VARCHAR(180) NOT NULL,slug VARCHAR(180) NOT NULL,layout_json CLOB,theme VARCHAR(16) NOT NULL DEFAULT 'light',published BOOLEAN NOT NULL DEFAULT FALSE,updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,slug))",
            "CREATE TABLE IF NOT EXISTS purchase_threads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,product_id BIGINT NOT NULL,buyer_id BIGINT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'open',provider VARCHAR(24) NOT NULL DEFAULT 'manual',provider_ref VARCHAR(180),created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS purchase_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,thread_id BIGINT NOT NULL,user_id BIGINT NOT NULL,message CLOB NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS support_tickets (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT,product_id BIGINT,user_id BIGINT NOT NULL,subject VARCHAR(220) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'open',priority VARCHAR(24) NOT NULL DEFAULT 'normal',created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS support_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticket_id BIGINT NOT NULL,user_id BIGINT NOT NULL,message CLOB NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS integrations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,type VARCHAR(40) NOT NULL,config_json CLOB,enabled BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,type))",
            "CREATE TABLE IF NOT EXISTS infra_nodes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,name VARCHAR(140) NOT NULL,type VARCHAR(60) NOT NULL,url VARCHAR(600),status VARCHAR(24) NOT NULL DEFAULT 'unknown',metadata_json CLOB,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS api_keys (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT NOT NULL,name VARCHAR(120) NOT NULL,key_hash VARCHAR(128) NOT NULL UNIQUE,prefix VARCHAR(24) NOT NULL,scopes CLOB,revoked BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS platform_settings (setting_key VARCHAR(160) PRIMARY KEY,setting_value CLOB,updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS audit_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id BIGINT,user_id BIGINT,action VARCHAR(140) NOT NULL,target VARCHAR(220),details CLOB,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        );
        for (String sql : ddl) execute(sql);
    }

    public List<Map<String,Object>> query(String sql, Object... args) {
        try (Connection c=dataSource.getConnection(); PreparedStatement ps=c.prepareStatement(sql)) {
            bind(ps,args);
            try (ResultSet rs=ps.executeQuery()) {
                List<Map<String,Object>> out=new ArrayList<>();
                ResultSetMetaData md=rs.getMetaData();
                while(rs.next()) {
                    Map<String,Object> row=new LinkedHashMap<>();
                    for(int i=1;i<=md.getColumnCount();i++) row.put(md.getColumnLabel(i).toLowerCase(Locale.ROOT), rs.getObject(i));
                    out.add(row);
                }
                return out;
            }
        } catch(SQLException e){ throw new IllegalStateException("Database query failed",e); }
    }

    public Map<String,Object> one(String sql,Object...args){
        List<Map<String,Object>> rows=query(sql,args);
        return rows.isEmpty()?null:rows.getFirst();
    }

    public int execute(String sql,Object...args){
        try(Connection c=dataSource.getConnection(); PreparedStatement ps=c.prepareStatement(sql)){
            bind(ps,args); return ps.executeUpdate();
        }catch(SQLException e){throw new IllegalStateException("Database write failed",e);}
    }

    public long insert(String sql,Object...args){
        try(Connection c=dataSource.getConnection(); PreparedStatement ps=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){
            bind(ps,args); ps.executeUpdate();
            try(ResultSet rs=ps.getGeneratedKeys()){ if(rs.next()) return rs.getLong(1); }
            throw new IllegalStateException("Insert did not return an id");
        }catch(SQLException e){throw new IllegalStateException("Database insert failed",e);}
    }

    public long count(String sql,Object...args){
        Map<String,Object> row=one(sql,args);
        if(row==null||row.isEmpty()) return 0;
        Object v=row.values().iterator().next();
        return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));
    }

    private void bind(PreparedStatement ps,Object[] args)throws SQLException{
        for(int i=0;i<args.length;i++) ps.setObject(i+1,args[i]);
    }
}
