quarkus.http.port=${PORT:8088}
quarkus.package.jar.type=uber-jar
quarkus.http.limits.max-body-size=100M
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:${NORD_FORGE_DATA_DIR:/tmp/nord-forge}/db/forge;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=1
quarkus.smallrye-health.root-path=/q/health
quarkus.log.category."com.nordlab.forge".level=INFO
